sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then
      composer update -n --prefer-dist --ignore-platform-reqs;
    else
      composer update -n --prefer-dist;
    fi

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show
  - cd test/tls && ./regenerate.sh && cd -

script:
  # PHPDBG segfaults on versions other than 7.0 currently
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then
      phpdbg -qrr vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov;
    else
      vendor/bin/phpunit --coverage-text --verbose --coverage-php coverage/cov/main.cov;
    fi
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then
      coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
      ./coveralls.phar -v;
    fi

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
