sudo: false

language: php

php:
	- 5.5
	- 5.6
	- 7.0

install:
	- phpenv rehash
	- composer self-update
	- composer require satooshi/php-coveralls:dev-master
	- composer install

script:
	- $(php -r 'if (PHP_MAJOR_VERSION >= 7) echo "phpdbg -qrr"; else echo "php";') vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
	- php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
	- php vendor/bin/coveralls -v
