sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - composer update -n --prefer-dist

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show
  - cd test/tls && ./regenerate.sh && cd -

script:
  - vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache/files
